name: 'food_delivery_dbt'
version: '1.0.0'

profile: 'food_delivery_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  food_delivery_dbt:
    staging:
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: table

    marts:
      +schema: marts
      +materialized: table
       
